<?php

namespace ApiBundle\Entity\Repository;

/**
 * BestOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
