<?php

namespace ApiBundle\Entity\Repository;

/**
 * CiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonusMoneyRebateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBonusByOrderSum($sum)
    {
        return $this->createQueryBuilder('c')
            ->orderBy('c.orderPrice', 'DESC')
            ->andWhere('c.orderPrice <= :orderPrice')
            ->setParameter('orderPrice', $sum)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
    public function getBonusesAsArray()
    {
        return $this->createQueryBuilder('b')
            ->getQuery()
            ->getArrayResult();
    }
}
