<?php

namespace ApiBundle\Entity\Repository;

/**
 * CiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiteRepository extends \Doctrine\ORM\EntityRepository
{

}
