<?php

namespace ApiBundle\Entity\Repository;

/**
 * ContactMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getContactMessagesForBlock()
    {
        return $this->createQueryBuilder('c')
            ->orderBy('c.createdAt','DESC')
            ->setMaxResults(7)
            ->getQuery()
            ->getResult()
            ;
    }
}
