<?php

namespace ApiBundle\Entity\Repository;

/**
 * CoverGalleryImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoverGalleryImageRepository extends \Doctrine\ORM\EntityRepository
{
}
