<?php

namespace ApiBundle\Entity\Repository;

/**
 * CoverTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoverTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
