<?php

namespace ApiBundle\Entity\Repository;

/**
 * CustomCoverGalleryTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomCoverGalleryTextRepository extends \Doctrine\ORM\EntityRepository
{
}
