<?php

namespace ApiBundle\Entity\Repository;

/**
 * CustomCoverGalleryImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomCoverGalleryImageRepository extends \Doctrine\ORM\EntityRepository
{
}
