<?php

namespace ApiBundle\Entity\Repository;

/**
 * CustomCoverTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomCoverTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
