<?php

namespace ApiBundle\Entity\Repository;

/**
 * FilterMaterialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterMaterialRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFilterMaterials(){
        return $this->createQueryBuilder('m')
            ->orderBy('m.title','ASC')
            ;
    }
}
