<?php

namespace ApiBundle\Entity\Repository;

/**
 * FilterItemTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterItemTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFilterItemTypes(){
        return $this->createQueryBuilder('i')
            ->orderBy('i.title','ASC')
            ;
    }
}
