<?php

namespace ApiBundle\Entity\Repository;

/**
 * FilterConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterConfigRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByPage($page){
        return $this->createQueryBuilder('f')
            ->select('f,cl,tp,tg,mt')
            ->leftJoin('f.colors','cl')
            ->leftJoin('f.itemTypes','tp')
            ->leftJoin('f.tags','tg')
            ->leftJoin('f.materials','mt')
            ->where('f.page = :page')
            ->setParameter('page',$page)
            ->getQuery()
            ->getSingleResult()
            ;
    }
}
