<?php

namespace ApiBundle\Entity\Repository;

/**
 * FilterColorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterColorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFilterColors(){
        return $this->createQueryBuilder('c')
            ->orderBy('c.title','ASC')
            ;
    }
}
