<?php

namespace ApiBundle\Entity\Repository;

/**
 * NonStandartCoverGalleryImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NonStandartCoverGalleryImageRepository extends \Doctrine\ORM\EntityRepository
{
}
