<?php

namespace ApiBundle\Entity\Repository;

/**
 * NovaPoshtaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NovaPoshtaDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRefreshStateOrdersByIds($ids)
    {
        $qb = $this->createQueryBuilder('np');

        return $qb
            ->andWhere("np.invoiceId IN(:ids)")
            ->setParameter('ids', array_values($ids))
            ->getQuery()
            ->getResult();
    }

    /**
     * get all orders with invoice but not received yet
     * 9, 10, 106 -    Одержано
     *
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getRefreshStateOrders()
    {
        $qb = $this->createQueryBuilder('np');
        $conditions = null;
        $conditions[] = $qb->expr()->not('np.isTrackNewPostState = 0');
        $orX = $qb->expr()->orX();
        $orX->addMultiple($conditions);

        $results = $qb
            ->where($orX)
            ->andWhere('np.invoiceId IS NOT NULL')
            ->getQuery()
            ->getResult();

        return $results;
    }

    public function getNpStateFilterQuery()
    {
        return $this->createQueryBuilder('np')
            ->orderBy('np.id', 'ASC');
//            ->getQuery();
    }
}
