<?php

namespace ApiBundle\Entity\Repository;

/**
 * NsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWithCovers($ids){
        return $this->createQueryBuilder('ct','ct.id')
            ->select('ct,cv,ph,v')
            ->leftJoin('ct.covers','cv','WITH', 'cv.id IN (:ids)')
            ->leftJoin('cv.phones','ph')
            ->leftJoin('ph.vendor','v')
            ->setParameter('ids',$ids)
            ->getQuery()
            ->getResult()
            ;
    }
    public function getAllIndexByIds(){
        return $this->createQueryBuilder('ct','ct.id')
            ->select('ct')
            ->getQuery()
            ->getResult()
            ;
    }
    public function getArrayList(){
        $categories = $this->createQueryBuilder('c','c.id')
            ->select('c.id,c.title')
            ->getQuery()
            ->getArrayResult();
        $result=[];
        if($categories){
            foreach ($categories as $category){
                $result[$category['title']]=$category['id'];
            }
        }
        return $result;
    }
}
