<?php

namespace ApiBundle\Entity\Repository;

/**
 * OrderHasCoverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderHasCoverRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByOrderAndItem($ordeId,$id,$phone=null){
        return $this->createQueryBuilder('c')
            ->leftJoin('c.order','o')
            ->leftJoin('c.cover','cov')
            ->leftJoin('c.customCover','cust')
            ->where('o.id = :oId')
            ->andWhere('cov.id = :cId OR cust.id = :cId')
            ->setParameter('oId',$ordeId)
            ->setParameter('cId',$id)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
    public function getByOrderAndCover($order,$cover){
        if(!$order||!$cover)return null;
        return $this->createQueryBuilder('c')
            ->leftJoin('c.order','o')
            ->leftJoin('c.cover','cov')
            ->leftJoin('c.customCover','cust')
            ->where('o.id = :oId')
            ->andWhere('cov.id = :cId')
            ->setParameter('oId',$order)
            ->setParameter('cId',$cover)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
