<?php

namespace ApiBundle\Entity\Repository;

/**
 * OrderHasNonStandartCoverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderHasNonStandartCoverRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByOrderAndItem($ordeId,$id,$phone=null){
        $q = $this->createQueryBuilder('c')
            ->leftJoin('c.order','o')
            ->leftJoin('c.cover','cov')
            ->leftJoin('c.phone','ph')
            ->where('o.id = :oId')
            ->andWhere('cov.id = :cId')
            ->setParameter('oId',$ordeId)
            ->setParameter('cId',$id)
            ;
        if($phone){
            $q
                ->andWhere('ph.slug = :phone')
                ->setParameter('phone',$phone)
            ;
        }else{
            $q->andWhere('ph IS NULL');
        }
        return $q
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
    public function getByOrderPhoneAndCover($order,$phone,$cover){
        if(!$order||!$phone||!$cover)return null;
        return $this->createQueryBuilder('c')
            ->leftJoin('c.order','o')
            ->leftJoin('c.cover','cov')
            ->leftJoin('c.phone','ph')
            ->where('o.id = :oId')
            ->andWhere('cov.id = :covId')
            ->andWhere('ph.id = :phone')
            ->setParameter('phone',$phone->getId())
            ->setParameter('oId',$order->getId())
            ->setParameter('covId',$cover->getId())
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
