<?php

namespace ApiBundle\Entity\Repository;

/**
 * OrderDeliveryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDeliveryTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
