<?php

namespace ApiBundle\Entity\Repository;

/**
 * OrderHasProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderHasProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByOrderAndItem($ordeId,$id,$phone=null){
        $q = $this->createQueryBuilder('c')
            ->leftJoin('c.order','o')
            ->leftJoin('c.product','p')
            ->leftJoin('c.phone','ph')
            ->where('o.id = :oId')
            ->andWhere('p.id = :pId')
            ->setParameter('oId',$ordeId)
            ->setParameter('pId',$id)
            ;
        if($phone){
            $q
                ->andWhere('ph.slug = :phone')
                ->setParameter('phone',$phone)
            ;
        }else{
            $q->andWhere('c.phone IS NULL');
        }
        return $q
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
    public function getByOrderPhoneAndProduct($order,$phone,$product){
        if(!$order||!$phone||!$product)return null;
        return $this->createQueryBuilder('c')
            ->leftJoin('c.order','o')
            ->leftJoin('c.product','p')
            ->leftJoin('c.phone','ph')
            ->where('o.id = :oId')
            ->andWhere('p.id = :pId')
            ->andWhere('ph.id = :phone')
            ->setParameter('phone',$phone->getId())
            ->setParameter('oId',$order->getId())
            ->setParameter('pId',$product->getId())
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
