<?php

namespace ApiBundle\Entity\Repository;

/**
 * PatternGalleryImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatternGalleryImageRepository extends \Doctrine\ORM\EntityRepository
{
}
