<?php

namespace ApiBundle\Entity\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * PatternRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatternTagsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getArr() {
        return $this->createQueryBuilder('v')
            ->leftJoin('v.patterns','patterns')
//            ->leftJoin('v.pattern','pattern')
//            ->leftJoin('v.transparentImages','transparentImages')
            ->leftJoin('v.products','products')
            ->select('v, partial patterns.{id,title}, partial products.{id, title}')
            ->getQuery()
//            ->setMaxResults(100)
            ->getArrayResult();

    }

    public function getAllSortedByTitle()
    {
        $query = $this->createQueryBuilder('t')
            ->orderBy('t.title', 'ASC')
            ->getQuery();
        return $query;
    }
    public function getFilterTags(){
        return $this->createQueryBuilder('t')
            ->orderBy('t.title','ASC')
            ;
    }
}
