<?php

namespace ApiBundle\Entity\Repository;

/**
 * PhoneCoverTypeDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneCoverTypeDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
