<?php

namespace ApiBundle\Entity\Repository;

/**
 * PhoneBackgroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneBackgroundRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArr() {
        return $this->createQueryBuilder('v')
            ->leftJoin('v.phone', 'phone')
            ->leftJoin('v.transparentImages', 'transparentImages')
            ->select('v, transparentImages, partial phone.{id, title}')
            ->getQuery()
            ->getArrayResult();
    }
}
