<?php

namespace ApiBundle\Entity\Repository;

/**
 * PhoneBackgroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneBackgroundRepository extends \Doctrine\ORM\EntityRepository
{
}
