<?php

namespace ApiBundle\Entity\Repository;

/**
 * ProductGalleryImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductGalleryImageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getArr() {
        return $this->createQueryBuilder('v')
            ->leftJoin('v.product', 'gallery')
            ->select('v, partial gallery.{id, title}')
            ->getQuery()
            ->getArrayResult();
    }
}
