<?php

namespace ApiBundle\Entity\Repository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkPromo($code)
    {
        $today = new \DateTime('now');
        return $this->createQueryBuilder('p')
            ->where('p.promoCode = :code')
            ->andWhere("p.deadLine >= :today")
            ->andWhere("p.status  = :active")
            ->setParameter('code', $code)
            ->setParameter('today', $today)
            ->setParameter('active', 'active')
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
