<?php

namespace ApiBundle\Entity\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * RecallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecallRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRecallsForBlock()
    {
        return $this->createQueryBuilder('r')
            ->orderBy('r.createdAt','DESC')
            ->setMaxResults(7)
            ->getQuery()
            ->getResult()
            ;
    }
    public function getRecallsLimitBy($lim = 2, $offset = 0)
    {
        return $this->createQueryBuilder('r')
            ->orderBy('r.createdAt','DESC')
            ->setMaxResults($lim)
            ->getQuery()
            ->getResult()
            ;
//        $query = $this->createQueryBuilder('r')
////            ->where('r.status != :non')
//            ->orderBy('r.createdAt','DESC')
////            ->setParameter('non', 'new')
//            ->getQuery()
//            ->setMaxResults($lim)
//            ->setFirstResult($offset);
//        $results = new Paginator($query, $fetchJoin = true);
//        return $results;
    }
    public function getAllSortedByDate()
    {
        $query = $this->createQueryBuilder('r')
//            ->where('r.status != :non')
            ->orderBy('r.createdAt', 'DESC')
//            ->setParameter('non', 'NON')
            ->getQuery()
            ->getResult();
        return $query;
    }
}
