<?php

namespace ApiBundle\Entity\Repository;

/**
 * ShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSortedByTitle(){
        return  $this->createQueryBuilder('s')
                    ->orderBy('s.title',"ASC")
                    ->getQuery();
    }
    public function getOneByTitle($title){
        return $this->createQueryBuilder('s')
            ->where('s.title LIKE :title')
            ->andWhere('s.deadLine > :time')
            ->setParameter('title',$title)
            ->setParameter('time',time())
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
