<?php

namespace ApiBundle\Entity\Repository;

/**
 * StaticContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticContentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByPage($page)
    {
        $query = $this->createQueryBuilder('s')
            ->where('s.page = :page')
            ->setParameter('page', $page)
            ->getQuery()
            ->getResult();
        $final=array();
        if($query){
            foreach($query as $res)
            {
                $final[$res->getLinkname()]=$res;
            }
        }
        return $final;
    }
}
