<?php

namespace ApiBundle\Entity\Repository;

/**
 * TransparentImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransparentImageRepository extends \Doctrine\ORM\EntityRepository
{
}
