<?php

namespace ApiBundle\Entity\Repository;

/**
 * UkrPoshtaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UkrPoshtaDataRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * get all orders with invoice but not received yet
     *
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getRefreshStateOrders()
    {
        $qb = $this->createQueryBuilder('up');
//        $conditions = null;
//        $conditions[] = $qb->expr()->not('np.isTrackNewPostState = 0');
//        $orX = $qb->expr()->orX();
//        $orX->addMultiple($conditions);

        $results = $qb
//            ->where($orX)
            ->andWhere('up.invoiceId IS NOT NULL')
            ->getQuery()
            ->getResult();

        return $results;
    }
}
