<?php

namespace ApiBundle\Entity\Repository;

/**
 * UkrPoshtaRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UkrPoshtaRegionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllIndexById(){
        $q = $this->createQueryBuilder('upr')
            ->select('upr.regUa, upr.regId')
            ->getQuery()
            ->getArrayResult();
        $arr=[];
        if(count($q)){
            $arr = array_column($q,'regUa','regId');
        }
        return $arr;
    }
}
