<?php

namespace ApiBundle\Entity\Repository;

/**
 * UkrPoshtaSenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UkrPoshtaSenderRepository extends \Doctrine\ORM\EntityRepository
{
}
